#!/usr/bin/env python3
"""Regenerate INVENTORY.json for a repo-dna-results vault checkout.

Usage: rebuild_vault_inventory.py <path-to-vault-checkout>
Walks <vault>/extracts and writes <vault>/INVENTORY.json.
"""
import hashlib
import json
import pathlib
import sys

vault = pathlib.Path(sys.argv[1])
root = vault / "extracts"

items = []
repos = set()
crystal_repos = set()
for p in sorted(root.rglob("*")):
    if not p.is_file():
        continue
    data = p.read_bytes()
    rel = p.relative_to(vault)
    items.append({
        "path": str(rel),
        "bytes": len(data),
        "sha256_12": hashlib.sha256(data).hexdigest()[:12],
    })
    parts = rel.parts  # extracts/owner/repo/...
    if len(parts) >= 3:
        repo_key = f"{parts[1]}/{parts[2]}"
        repos.add(repo_key)
        if p.name == "09_crystals.json":
            crystal_repos.add(repo_key)

inventory = {
    "schema": "dna-results-inventory.1",
    "extracts_in_git": len(repos),
    "crystals_in_git": len(crystal_repos),
    "note": "Auto-regenerated by repo-dna-system's dna.yml commit-back step.",
    "items": items,
}
(vault / "INVENTORY.json").write_text(json.dumps(inventory, indent=2) + "\n")
